epoch: 10
lr: 0.0001
weight_decay: 5.0e-5
batch_size: 16
contrastive_loss: true
training_with_cross_val: true
folds: 5
skip_k_fold: false
entire_training_set: false
subgraph_ablation: false
loss_ablation_m: false
loss_ablation_c: false
eval_only_c: false
continue_training: 0
continue_training_model: null
model_name: null
scannet: false
scanscribe_auto_gen: false
