data_root: ${oc.env:WHEREAMI_DATA_ROOT, ./data}
graphs_dir: ${paths.data_root}/processed_data
checkpoint_dir: ${paths.data_root}/model_checkpoints/graph2graph

# 3DSSG
3dssg_graphs: ${paths.graphs_dir}/3dssg/3dssg_graphs_processed_edgelists_relationembed.pt

# ScanScribe
scanscribe_train: ${paths.graphs_dir}/training/scanscribe_graphs_train_final_no_graph_min.pt
scanscribe_test: ${paths.graphs_dir}/testing/scanscribe_graphs_test_final_no_graph_min.pt
scanscribe_auto_gen: ${paths.graphs_dir}/scanscribe/scanscribe_text_graphs_from_image_desc_node_edge_features.pt

# Human
human_graphs: ${paths.graphs_dir}/human/human_graphs_processed.pt

# 3RScan mesh root
3rscan_root: ${oc.env:RSCAN_ROOT, null}

# Query root (frame JSONs with GT poses)
query_root: null
